import type { Metadata } from "next"
import { Inter, Karla, Poppins } from "next/font/google"
import { auth } from "@/auth"
import { ThemeProvider } from "@/context/theme-provider"
import { GeistSans } from "geist/font/sans"
import { SessionProvider } from "next-auth/react"

import { Toaster } from "@/components/ui/toaster"
import Navbar from "@/components/navbar"

import "./globals.css"

const inter = Inter({ subsets: ["latin"] })
const karla = Karla({ subsets: ["latin"] })
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "600"] })
const geist = GeistSans

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  let session = await auth()
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geist.className} h-screen w-screen`}
    >
      <body className="h-full w-full">
        <SessionProvider session={session}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />

            <main className="p-5">{children}</main>
            <Toaster />
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
