import type { Metadata } from "next"
import { Karla } from "next/font/google"
import { auth } from "@/auth"
import ProviderTree from "@/context/provider-tree"

import Navbar from "@/components/navbar"

import "./globals.css"

const karla = Karla({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  let session = await auth()
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${karla.className} h-screen w-screen`}
    >
      <body className="flex h-full w-full flex-col">
        <ProviderTree session={session}>
          <Navbar />
          <main className="flex-1 p-5">{children}</main>
        </ProviderTree>
      </body>
    </html>
  )
}
